### ISSUE TITLE
updated ouput

### ISSUE THREAD

**Issue by abrelsfo** [dawsonbotsford/sist#3]
[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Microsoft Windows 7 Enterprise
Windows_NT
x64

### node
`npm -v`: 3.7.5
`node --version`: v5.7.0

Time created: Fri Mar 04 2016 16:07:02 GMT-0500 (Eastern Standard Time)

### Description
Command: sist node

Always adds OS. The OS Name is only for windows but the other two should work for mac, linux, and SunOS

**Comment by dawsonbotsford** [comment]
You can edit your original issue with the pencil button in the top right. Closing, and copying this text over.
